(defun my-last (lst)
	(cond ((null (cdr lst)) lst)
		  (t (my-last (cdr lst)))
	)
)

(defun without-last (lst)
	(cond ((null (cdr lst)) nil)
		  ((null (cddr lst))(cons (car lst) Nil))
		  (t (append (cons (car lst) Nil) (without-last (cdr lst))))
	)
)

(defun swap-first-last (lst)
	(cond ((null (cdr lst)) lst)
		  (t (append (my-last lst) 
			      (without-last (cdr lst))
				  (cons (car lst) Nil)))
	)
)