(defun my-assoc (key table)
	(cond ((null table) nil)
		  ((if (equal key (caar table))
				(cdar table)
				(my-assoc key (cdr table))))
	)
)

(defun my-rassoc (val table)
	(cond ((null table) nil)
		  ((if (equal val (cdar table))
				(caar table)
				(my-rassoc val (cdr table))))
	)
)
