(defun my-nth (n lst)
	(cond ((< n 0) nil)
		  ((= n 0)(car lst))
		  (t (my-nth (- n 1) (cdr lst)))
	)
)

(defun my-nsubst (new n lst)
	(cond ((= n 0)(setf (car lst) new))
		  (t (my-nsubst new (- n 1) (cdr lst)))
	)
)

(defun swap-two-elements (lst n1 n2)
	(let ((el1 (my-nth n1 lst))
		  (el2 (my-nth n2 lst)))
	(if (and el1 el2)
		(and	(my-nsubst el2 n1 lst)
				(my-nsubst el1 n2 lst)
				lst)
		(print "ERROR: wrong index")))
)